export const taskItems = [
  {
    title: "Science & Nature Quiz",
    desc: "Test your knowledge of the natural world and earn $0.3 per correct answer.",
    bg: "bg-green-50",
    cta: "Take Quiz",
    icon: "🧪",
    link: "/quizpage",
  },
  {
    title: "Photo Hunt",
    desc: "Take a photo of a nearby market.",
    bg: "bg-orange-50",
    cta: "Start Task",
    icon: "📷",
    link: "/taskspage",
  },
  {
    title: "Tech & Innovation Quiz",
    desc: "Identify modern breakthroughs in tech.",
    bg: "bg-indigo-50",
    cta: "Take Quiz",
    icon: "💻",
    link: "/quizpage",
  },
  {
    title: "Transcribe Handwritten Note",
    desc: "Type out content from an uploaded image.",
    bg: "bg-yellow-50",
    cta: "Start Task",
    icon: "⌨️",
    link: "/taskspage",
  },
  {
    title: "Geography Quiz",
    desc: "Answer questions on world landmarks.",
    bg: "bg-blue-50",
    cta: "Take Quiz",
    icon: "🌍",
    link: "/quizpage",
  },
  {
    title: "Spin Challenge",
    desc: "Get lucky and win up to $50.",
    bg: "bg-pink-50",
    cta: "Spin Now",
    icon: "🎯",
    link: "/quizpage",
  },
  {
    title: "Local Language Quiz",
    desc: "Translate these common Yoruba phrases.",
    bg: "bg-purple-50",
    cta: "Take Quiz",
    icon: "🗣️",
    link: "/quizpage",
  },
  {
    title: "Short Video Task",
    desc: "Record a short 10-sec video about your workspace.",
    bg: "bg-rose-50",
    cta: "Start Task",
    icon: "🎥",
    link: "/taskspage",
  },
  {
    title: "Math & Logic Quiz",
    desc: "Solve logic problems to earn points.",
    bg: "bg-cyan-50",
    cta: "Take Quiz",
    icon: "🧠",
    link: "/quizpage",
  },
  {
    title: "Feedback Survey",
    desc: "Fill a quick form to share your opinion.",
    bg: "bg-lime-50",
    cta: "Start Task",
    icon: "📝",
    link: "/taskspage",
  },
  {
    title: "Landmark Photo Quest",
    desc: "Snap a picture of a major local landmark.",
    bg: "bg-amber-50",
    cta: "Start Task",
    icon: "🏛️",
    link: "/taskspage",
  },
  {
    title: "Spin & Win Bonus Round",
    desc: "Bonus spin unlocked — try your luck!",
    bg: "bg-red-50",
    cta: "Spin Now",
    icon: "🎰",
    link: "/quizpage",
  },
];
