export const taskItems = [
  {
    id: 1,
    task: "Rate the 'X Finance' app 5 stars on the Play Store",
    category: "app",
    reward: 0.75,
  },
  {
    id: 2,
    task: "Leave a 5-star review on 'ShopEase' app",
    category: "app",
    reward: 0.8,
  },
  {
    id: 3,
    task: "Like and comment on @CryptoBuzz's latest Instagram post",
    category: "social",
    reward: 0.5,
  },
  {
    id: 4,
    task: "Subscribe to 'X Tech Reviews' YouTube channel",
    category: "content",
    reward: 0.4,
  },
  {
    id: 5,
    task: "Like and rate the latest video from 'Finance Mastery'",
    category: "content",
    reward: 0.6,
  },
  {
    id: 6,
    task: "Share @MarketPro's latest post on Twitter",
    category: "social",
    reward: 0.45,
  },
  {
    id: 7,
    task: "Join the Telegram group for 'SmartTrade AI'",
    category: "community",
    reward: 0.6,
  },
  {
    id: 8,
    task: "Follow @InvestToday on Twitter and rate the link page 5 stars",
    category: "social",
    reward: 0.5,
  },
  {
    id: 9,
    task: "Download and rate the 'Daily Rewards' app 5 stars",
    category: "app",
    reward: 0.9,
  },
  {
    id: 10,
    task: "Bookmark and rate the article on 'Top 10 Crypto Tips of 2025'",
    category: "content",
    reward: 0.35,
  },
  {
    id: 11,
    task: "Like 3 videos from 'Passive Income Lab' and give a 5-star channel rating",
    category: "content",
    reward: 0.7,
  },
  {
    id: 12,
    task: "Follow @HealthyCrypto on Instagram and like the top 2 posts",
    category: "social",
    reward: 0.4,
  },
  {
    id: 13,
    task: "Rate the 'TaskForce Survey' app 5 stars and submit a review",
    category: "app",
    reward: 0.85,
  },
  {
    id: 14,
    task: "Comment 'Great content!' on @FutureWealth TikTok post",
    category: "social",
    reward: 0.5,
  },
  {
    id: 15,
    task: "Watch a full video and rate 'CryptoForYou' YouTube channel 5 stars",
    category: "content",
    reward: 0.6,
  },
  {
    id: 16,
    task: "Join the WhatsApp group for 'EarnIt Daily'",
    category: "community",
    reward: 0.55,
  },
  {
    id: 17,
    task: "Like and retweet @TradeZoneHQ's pinned tweet",
    category: "social",
    reward: 0.4,
  },
  {
    id: 18,
    task: "Upvote and comment on 'X Wallet' thread on Reddit",
    category: "social",
    reward: 0.5,
  },
  {
    id: 19,
    task: "Add a 5-star review on App Store for 'InvestBot'",
    category: "app",
    reward: 0.9,
  },
  {
    id: 20,
    task: "Rate and share 'Smart Savings' app 5 stars",
    category: "app",
    reward: 0.85,
  },
  {
    id: 21,
    task: "Follow @DeFiDojo on Twitter and comment on a recent post",
    category: "social",
    reward: 0.5,
  },
  {
    id: 22,
    task: "Download, explore and rate the 'CashFlow Tracker' app 5 stars",
    category: "app",
    reward: 0.8,
  },
  {
    id: 23,
    task: "Comment an emoji on the latest IG reel by @FinanceTipsDaily",
    category: "social",
    reward: 0.35,
  },
  {
    id: 24,
    task: "Subscribe to the earnquickly.co newsletter and rate it 5 stars",
    category: "community",
    reward: 0.55,
  },
  {
    id: 25,
    task: "Click and visit the landing page of 'AI Trader Bot' and give 5-star feedback",
    category: "content",
    reward: 0.5,
  },
  {
    id: 26,
    task: "Share 'Crypto Basics 101' article on Facebook and rate the site 5 stars",
    category: "content",
    reward: 0.45,
  },
  {
    id: 27,
    task: "Follow @YieldMakers on TikTok and like their top 3 posts",
    category: "social",
    reward: 0.6,
  },
  {
    id: 28,
    task: "Like and save the last 2 posts by @ProfitWave on Instagram",
    category: "social",
    reward: 0.45,
  },
  {
    id: 29,
    task: "Leave a 5-star review on Trustpilot for 'EarnBuddy'",
    category: "community",
    reward: 0.9,
  },
  {
    id: 30,
    task: "Complete your profile and leave a 5-star feedback on 'DailyBucks'",
    category: "app",
    reward: 0.65,
  },
];
