export const taskItems = [
  {
    id: 1,
    task_id: "rate-x-finance",
    title: "Rate the 'X Finance' App",
    desc: "Visit the Play Store, install and leave a 5-star review on the 'X Finance' app.",
    reward: 0.75,
    category: "app",
    link: "https://play.google.com/store/apps/details?id=x.finance",
    cta: "Rate on Play Store",
  },
  {
    id: 2,
    task_id: "review-shopease",
    title: "Review the 'ShopEase' App",
    desc: "Leave a 5-star review and feedback for the 'ShopEase' app on the Play Store.",
    reward: 0.8,
    category: "app",
    link: "https://play.google.com/store/apps/details?id=shopease",
    cta: "Leave Review",
  },
  {
    id: 3,
    task_id: "like-comment-cryptobuzz",
    title: "Engage with @CryptoBuzz on Instagram",
    desc: "Like and leave a comment on the latest post by @CryptoBuzz on Instagram.",
    reward: 1,
    category: "social",
    link: "https://instagram.com/cryptobuzz",
    cta: "Go to Post",
  },
  {
    id: 4,
    task_id: "subscribe-x-tech-reviews",
    title: "Subscribe to 'X Tech Reviews'",
    desc: "Subscribe to the 'X Tech Reviews' YouTube channel and turn on notifications.",
    reward: 2,
    category: "content",
    link: "https://youtube.com/@xtechreviews",
    cta: "Subscribe",
  },
  {
    id: 5,
    task_id: "rate-finance-mastery",
    title: "Rate Finance Mastery Video",
    desc: "Like and rate the latest video from 'Finance Mastery'.",
    reward: 0.2,
    category: "content",
    link: "https://youtube.com/@financemastery",
    cta: "Watch & Rate",
  },
  {
    id: 6,
    task_id: "share-marketpro-twitter",
    title: "Share @MarketPro Post",
    desc: "Share the latest post from @MarketPro on your Twitter timeline.",
    reward: 0.45,
    category: "social",
    link: "https://twitter.com/marketpro",
    cta: "Visit Twitter",
  },
  {
    id: 7,
    task_id: "join-smarttrade-telegram",
    title: "Join SmartTrade AI Telegram Group",
    desc: "Join the SmartTrade AI Telegram community and stay updated.",
    reward: 0.6,
    category: "community",
    link: "https://t.me/smarttradeai",
    cta: "Join Group",
  },
  {
    id: 8,
    task_id: "follow-investtoday-twitter",
    title: "Follow & Rate InvestToday",
    desc: "Follow @InvestToday on Twitter and rate their link page 5 stars.",
    reward: 0.5,
    category: "social",
    link: "https://twitter.com/investtoday",
    cta: "Follow Now",
  },
  {
    id: 9,
    task_id: "rate-daily-rewards-app",
    title: "Rate the 'Daily Rewards' App",
    desc: "Install and rate the 'Daily Rewards' app 5 stars.",
    reward: 0.9,
    category: "app",
    link: "https://play.google.com/store/apps/details?id=daily.rewards",
    cta: "Install & Rate",
  },
  {
    id: 10,
    task_id: "bookmark-crypto-tips-article",
    title: "Bookmark Crypto Tips Article",
    desc: "Bookmark and rate the 'Top 10 Crypto Tips of 2025' article.",
    reward: 0.35,
    category: "content",
    link: "https://example.com/top-10-crypto-tips",
    cta: "Read Article",
  },
  {
    id: 11,
    task_id: "like-passive-income-lab",
    title: "Like Passive Income Lab Videos",
    desc: "Like 3 videos from 'Passive Income Lab' and give the channel a 5-star rating.",
    reward: 0.7,
    category: "content",
    link: "https://youtube.com/@passiveincomelab",
    cta: "Watch & Like",
  },
  {
    id: 12,
    task_id: "follow-healthycrypto-instagram",
    title: "Follow @HealthyCrypto",
    desc: "Follow @HealthyCrypto on Instagram and like their top 2 posts.",
    reward: 0.4,
    category: "social",
    link: "https://instagram.com/healthycrypto",
    cta: "Open Instagram",
  },
  {
    id: 13,
    task_id: "review-taskforce-survey",
    title: "Review TaskForce Survey App",
    desc: "Rate the TaskForce Survey app 5 stars and leave a brief review.",
    reward: 0.85,
    category: "app",
    link: "https://play.google.com/store/apps/details?id=taskforce.survey",
    cta: "Rate App",
  },
  {
    id: 14,
    task_id: "comment-futurewealth-tiktok",
    title: "Comment on FutureWealth Post",
    desc: "Comment 'Great content!' on the latest TikTok video by @FutureWealth.",
    reward: 0.5,
    category: "social",
    link: "https://tiktok.com/@futurewealth",
    cta: "Go to TikTok",
  },
  {
    id: 15,
    task_id: "rate-cryptoforyou-youtube",
    title: "Rate CryptoForYou",
    desc: "Watch a full video and rate 'CryptoForYou' YouTube channel 5 stars.",
    reward: 0.6,
    category: "content",
    link: "https://youtube.com/@cryptoforyou",
    cta: "Watch Now",
  },
  {
    id: 16,
    task_id: "join-earnit-whatsapp",
    title: "Join EarnIt Daily WhatsApp",
    desc: "Join the EarnIt Daily WhatsApp group to connect with the team.",
    reward: 0.55,
    category: "community",
    link: "https://wa.me/2348123456789",
    cta: "Join WhatsApp Group",
  },
  {
    id: 17,
    task_id: "retweet-tradezonehq",
    title: "Retweet @TradeZoneHQ",
    desc: "Like and retweet the pinned tweet by @TradeZoneHQ.",
    reward: 0.4,
    category: "social",
    link: "https://twitter.com/tradezonehq",
    cta: "Retweet Now",
  },
  {
    id: 18,
    task_id: "upvote-x-wallet-reddit",
    title: "Upvote X Wallet Thread",
    desc: "Upvote and leave a comment on the Reddit thread about 'X Wallet'.",
    reward: 0.5,
    category: "social",
    link: "https://reddit.com/r/cryptocurrency",
    cta: "Open Reddit",
  },
  {
    id: 19,
    task_id: "review-investbot-ios",
    title: "Review InvestBot on iOS",
    desc: "Leave a 5-star review on the App Store for the 'InvestBot' app.",
    reward: 0.9,
    category: "app",
    link: "https://apps.apple.com/us/app/investbot/id123456789",
    cta: "Open App Store",
  },
  {
    id: 20,
    task_id: "rate-smart-savings",
    title: "Rate Smart Savings App",
    desc: "Rate and share the Smart Savings app 5 stars on the store.",
    reward: 0.85,
    category: "app",
    link: "https://play.google.com/store/apps/details?id=smartsavings",
    cta: "Install & Share",
  },
  {
    id: 21,
    task_id: "comment-defidojo",
    title: "Engage with @DeFiDojo",
    desc: "Follow @DeFiDojo on Twitter and comment on one of their recent tweets.",
    reward: 0.5,
    category: "social",
    link: "https://twitter.com/defidojo",
    cta: "Follow & Comment",
  },
  {
    id: 22,
    task_id: "review-cashflow-tracker",
    title: "Rate CashFlow Tracker App",
    desc: "Download, explore and give a 5-star rating to the 'CashFlow Tracker' app.",
    reward: 0.8,
    category: "app",
    link: "https://play.google.com/store/apps/details?id=cashflow.tracker",
    cta: "Download App",
  },
  {
    id: 23,
    task_id: "emoji-financetipsdaily",
    title: "Emoji Comment on IG",
    desc: "Comment an emoji on the latest Instagram reel by @FinanceTipsDaily.",
    reward: 0.35,
    category: "social",
    link: "https://instagram.com/financetipsdaily",
    cta: "Open Reel",
  },
  {
    id: 24,
    task_id: "subscribe-earnquickly",
    title: "Subscribe to EarnQuickly Newsletter",
    desc: "Subscribe to earnquickly.co newsletter and give it a 5-star rating.",
    reward: 0.55,
    category: "community",
    link: "https://earnquickly.co",
    cta: "Subscribe",
  },
  {
    id: 25,
    task_id: "rate-ai-trader-landing",
    title: "Rate AI Trader Bot Landing Page",
    desc: "Click and visit the landing page of 'AI Trader Bot' and leave a 5-star feedback.",
    reward: 0.5,
    category: "content",
    link: "https://aitraderbot.io",
    cta: "Visit Page",
  },
  {
    id: 26,
    task_id: "share-crypto-basics-fb",
    title: "Share Crypto Basics Article",
    desc: "Share the 'Crypto Basics 101' article on Facebook and give the site a 5-star rating.",
    reward: 0.4,
    category: "content",
    link: "https://example.com/crypto-basics",
    cta: "Share & Rate",
  },
  {
    id: 27,
    task_id: "follow-yieldmakers-tiktok",
    title: "Engage with @YieldMakers",
    desc: "Follow @YieldMakers on TikTok and like their top 3 videos.",
    reward: 0.6,
    category: "social",
    link: "https://tiktok.com/@yieldmakers",
    cta: "Open TikTok",
  },
  {
    id: 28,
    task_id: "like-profitwave-ig",
    title: "Like ProfitWave's Instagram Posts",
    desc: "Like and save the last 2 Instagram posts by @ProfitWave.",
    reward: 0.45,
    category: "social",
    link: "https://instagram.com/profitwave",
    cta: "Visit Profile",
  },
  {
    id: 29,
    task_id: "review-earnbuddy-trustpilot",
    title: "Trustpilot Review for EarnBuddy",
    desc: "Leave a 5-star review on Trustpilot for EarnBuddy.",
    reward: 0.2,
    category: "community",
    link: "https://trustpilot.com/review/earnbuddy.com",
    cta: "Write Review",
  },
  {
    id: 30,
    task_id: "complete-dailybucks-profile",
    title: "Complete Profile on DailyBucks",
    desc: "Complete your profile on DailyBucks and leave a 5-star review.",
    reward: 0.65,
    category: "app",
    link: "https://dailybucks.io",
    cta: "Complete Profile",
  },
];
